<?php
	$collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('title') ?></th>
            <th scope="col" class="col email"><?php echo __('content') ?></th>
            <th scope="col" class="col telephone"><?php echo __('url_key') ?></th>
            <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
				foreach ($collection as $item){
                    print_r($item->getData());
                }
                 ?>
        
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
	}
	?>