<?php
	$collection = $block->getCollection();
if ($collection->count()) {
?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col name"><?php echo __('Title') ?></th>
            <th scope="col" class="col email"><?php echo __('Content') ?></th>
            <th scope="col" class="col telephone"><?php echo __('URL_KEY') ?></th>
            <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
				foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $item->getPost_id() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Title')) ?>" class="col name">
                <?php echo $item->getTitle() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Content')) ?>" class="col email">
                <?php echo $item->getContent() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('URL_KEY')) ?>" class="col telephone">
                <?php echo $item->getUrl_key() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
	}
	?>